version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: employee-mysql-dev
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'ben1234'
      MYSQL_DATABASE: 'employee-dev'
      MYSQL_USER: 'ben'
      MYSQL_PASSWORD: 'ben1234'
    volumes:
      - ./dev_data:/mysql